CREATE RESOURCE cpu (MASTER THREAD, WORKER THREAD);

CREATE WORKLOAD all SETTINGS max_concurrent_threads=60;

CREATE WORKLOAD SpeedUpOne IN all SETTINGS weight = 10;

CREATE WORKLOAD SpeedUpTwo IN all SETTINGS weight = 1;