CREATE RESOURCE cpu (MASTER THREAD, WORKER THREAD);

CREATE OR REPLACE WORKLOAD all SETTINGS max_concurrent_threads=120;

CREATE OR REPLACE WORKLOAD SpeedUpOne IN all SETTINGS weight=1;

CREATE OR REPLACE WORKLOAD SpeedUpTwo IN all SETTINGS weight=1;


