CREATE RESOURCE cpu (MASTER THREAD, WORKER THREAD);

CREATE WORKLOAD all SETTINGS max_concurrent_threads=120;

CREATE WORKLOAD SpeedUpOne IN all SETTINGS weight = 1;

CREATE WORKLOAD SpeedUpTwo IN all SETTINGS weight = 1;